mode: train
experiment_name: 250618_unet_resnet34

# Paths
old_images_dir: /home/moritz/masterarbeit/raster/KH-9/amsterdam/georeferenced/filtered
new_images_dir: /home/moritz/masterarbeit/raster/aerial_images_2023
bag_buildings_dir: /home/moritz/masterarbeit/vector/buildings
log_dir: /home/moritz/masterarbeit/early_fusion/logs
results_root: /home/moritz/masterarbeit/early_fusion/results
predictions_root: /home/moritz/masterarbeit/predictions
rois_path: /home/moritz/masterarbeit/vector/dataset_splits.gpkg

# Model
task: baseline
model: unet
backbone: resnet34
loss: focal

# Hyperparameters
batch_size: 5
patch_size: 1024
learning_rate: 0.0001
num_dataloader_workers: 11
val_split_pct: 0.2
test_split_pct: 0.1

# Optional
checkpoint_name: last
